//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerMe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeerMeEntities : DbContext
    {
        public BeerMeEntities()
            : base("name=BeerMeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<BeerCategory> BeerCategories { get; set; }
        public virtual DbSet<BeerStyle> BeerStyles { get; set; }
        public virtual DbSet<BeerABV> BeerABVs { get; set; }
        public virtual DbSet<BeerColor> BeerColors { get; set; }
        public virtual DbSet<BeerIBU> BeerIBUs { get; set; }
        public virtual DbSet<BeerRating> BeerRatings { get; set; }
        public virtual DbSet<Beer> Beers { get; set; }
    }
}
