//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeerColor
    {
        public int Id { get; set; }
        public string ColorName { get; set; }
        public int ColorValue { get; set; }
    }
}
