//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeerStyle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BeerStyle()
        {
            this.Beers = new HashSet<Beer>();
        }
    
        public int Id { get; set; }
        public string Style { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> ColorValue { get; set; }
        public Nullable<int> ABV { get; set; }
        public Nullable<int> IBU { get; set; }
    
        public virtual BeerCategory BeerCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beer> Beers { get; set; }
    }
}
